name: deploy-dev
run-name: Deploy AFL tracker web UI to Dev by @${{ github.actor }}
on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The image tag to deploy'
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.12'
          cache: 'npm'
          cache-dependency-path: './pulumi-infra/package-lock.json'
      
      - name: Install dependencies
        run: npm ci
        working-directory: ./pulumi-infra

      - name: Authenticate to Google Cloud
        id: gcloud-auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
        
      - name: Pulumi Deploy
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dev
          work-dir: ./pulumi-infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          GCP_ACCESS_TOKEN: ${{ steps.gcloud-auth.outputs.access_token }}
          PULUMI_CONFIG_PASSTHROUGH: | 
                gcp:project=${{ vars.GCP_PROJECT_ID }},\
                gcp:region=${{ vars.GCP_REGION }},\
                app-image=${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/afl-tracker-repo/afl-tracker-web:${GITHUB_SHA},\
                imageTag=${{ github.event.inputs.image_tag }}