name: Deploy Firebase Hosting

on:
  workflow_dispatch:

jobs:
  deploy-hosting:
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: gcloud-auth
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: ${{ vars.WIF_PROVIDER }}
          service_account: ${{ vars.APP_DEPLOYER_SERVICE_ACCOUNT }}

      - name: Install firebase-tools
        run: npm install -g firebase-tools

      - name: Deploy Firebase Hosting
        run: firebase deploy --only hosting --project ${{ vars.GCP_PROJECT_ID }}
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.gcloud-auth.outputs.credentials_file_path }}
